apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopizer-backend
  namespace: shopizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopizer-backend
  template:
    metadata:
      labels:
        app: shopizer-backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z shopizer-db 3306; do echo "Waiting for MySQL..."; sleep 3; done']
      containers:
        - name: backend
          image: ghcr.io/kumudamulgund/shopizer:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
