apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: shopizer
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: shopizer123
  MYSQL_DATABASE: shopizer
  MYSQL_USER: shopizer
  MYSQL_PASSWORD: shopizer123
