apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopizer-db
  namespace: shopizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopizer-db
  template:
    metadata:
      labels:
        app: shopizer-db
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
